#!/bin/bash

clear

# SSl vulnerability check
echo -e -n 'Performing SSL vulnerability check...\r'

a2sv -t $1 > a2sv_tmp.txt

echo '[*]SSL Vulnerabilities:                      '
cat a2sv_tmp.txt | grep CVE- | sort -u

rm a2sv_tmp.txt
echo ''

# Check for open ports
echo -e -n 'Checking for open ports...\r'

nmap $1 > nmap_tmp.txt

echo '[*]Open ports:                               '
cat nmap_tmp.txt | grep open

rm nmap_tmp.txt
echo ''

# Check for Vulnerabilities
echo -e -n 'Checking for vulnerabilities...\r'

nmap -sV --script vulners --script-args mincvss=5.0 $1 > nmap_cve_tmp.txt

echo '[*]Vulnerabilities:                          '
cat nmap_cve_tmp.txt | grep 'open\|CVE-'

rm nmap_cve_tmp.txt
